swagger: '2.0'
info:
  title: Documentation de l'API Bank Argent
  description: Contient tous les points de terminaison API disponibles dans cette base de code
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: User Login
      description: Authenticate a user and return a token
      parameters:
        - in: body
          name: body
          description: Login Credentials
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successful
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Credentials
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get User Profile
      description: Retrieve the profile of the authenticated user
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/UserProfile'
        '401':
          description: Unauthorized - Invalid or missing token
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Profile
      description: Update the profile of the authenticated user
      parameters:
        - in: body
          name: body
          description: Updated user information
          required: true
          schema:
            $ref: '#/definitions/UserProfileUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized - Invalid or missing token
        '500':
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Module Transaction
      summary: Liste des transactions de l'utilisateur
      description: Récupère une liste des transactions pour l'utilisateur authentifié
      produces:
        - application/json
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            $ref: '#/definitions/TransactionsList'
        '401':
          description: Non autorisé - Jeton invalide ou manquant
        '500':
          description: Erreur interne du serveur
  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Module Transaction
      summary: Obtenir les détails d'une transaction
      description: Récupère les détails d'une transaction spécifique
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à récupérer
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Non autorisé - Jeton invalide ou manquant
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
    patch:
      security:
        - Bearer: []
      tags:
        - Module Transaction
      summary: Mise à jour partielle de la transaction
      description: Met à jour des champs spécifiques d'une transaction (par exemple, catégorie ou note)
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à mettre à jour
          required: true
          type: string
        - in: body
          name: body
          description: Champs à mettre à jour
          required: true
          schema:
            $ref: '#/definitions/TransactionPartialUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction partiellement mise à jour avec succès
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Champs invalides
        '401':
          description: Non autorisé - Jeton invalide ou manquant
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Login:
    type: object
    properties:
      email:
        type: string
        description: User's email address
      password:
        type: string
        description: User's password
    required:
      - email
      - password
  LoginResponse:
    type: object
    properties:
      token:
        type: string
        description: JWT token for authentication
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
  UserProfileUpdate:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      category:
        type: string
      note:
        type: string
  TransactionsList:
    type: array
    items:
      $ref: '#/definitions/Transaction'
  TransactionUpdate:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      category:
        type: string
      note:
        type: string
  TransactionPartialUpdate:
    type: object
    properties:
      category:
        type: string
      note:
        type: string
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
