swagger: '2.0'
info:
  title: Argent Bank API
  description: API pour l'application front-end Argent Bank
  version: '1.0.0'
  termsOfService: 'http://example.com/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - Authentification
      summary: Connexion de l'utilisateur
      description: Authentifie un utilisateur et renvoie un token JWT
      parameters:
        - in: body
          name: credentials
          description: Identifiants de l'utilisateur
          required: true
          schema:
            $ref: '#/definitions/LoginCredentials'
      responses:
        '200':
          description: Connexion réussie
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Identifiants invalides
        '500':
          description: Erreur serveur

  /user/signup:
    post:
      tags:
        - Authentification
      summary: Inscription d'un nouvel utilisateur
      description: Crée un nouveau compte utilisateur
      parameters:
        - in: body
          name: userInfo
          description: Informations du nouvel utilisateur
          required: true
          schema:
            $ref: '#/definitions/SignUpCredentials'
      responses:
        '201':
          description: Compte créé avec succès
        '400':
          description: Données invalides
        '500':
          description: Erreur serveur

  /user/profile:
    get:
      tags:
        - Utilisateur
      summary: Récupérer le profil de l'utilisateur
      description: Récupère les informations du profil de l'utilisateur connecté
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Profil récupéré avec succès
          schema:
            $ref: '#/definitions/UserProfile'
        '401':
          description: Non autorisé
        '500':
          description: Erreur serveur
    put:
      tags:
        - Utilisateur
      summary: Mettre à jour le profil de l'utilisateur
      description: Met à jour les informations du profil de l'utilisateur connecté
      security:
        - BearerAuth: []
      parameters:
        - in: body
          name: profileUpdate
          description: Nouvelles informations du profil
          required: true
          schema:
            $ref: '#/definitions/ProfileUpdate'
      responses:
        '200':
          description: Profil mis à jour avec succès
          schema:
            $ref: '#/definitions/UserProfile'
        '400':
          description: Données invalides
        '401':
          description: Non autorisé
        '500':
          description: Erreur serveur

  /accounts:
    get:
      tags:
        - Comptes
      summary: Récupérer les comptes de l'utilisateur
      description: Récupère la liste des comptes de l'utilisateur connecté
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Comptes récupérés avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '401':
          description: Non autorisé
        '500':
          description: Erreur serveur

  /accounts/{accountId}/transactions:
    get:
      tags:
        - Transactions
      summary: Récupérer les transactions d'un compte
      description: Récupère la liste des transactions pour un compte spécifique
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '401':
          description: Non autorisé
        '404':
          description: Compte non trouvé
        '500':
          description: Erreur serveur

  /transactions/{transactionId}:
    put:
      tags:
        - Transactions
      summary: Mettre à jour une transaction
      description: Met à jour les détails d'une transaction spécifique
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
        - in: body
          name: transactionUpdate
          description: Nouvelles informations de la transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Transaction mise à jour avec succès
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Données invalides
        '401':
          description: Non autorisé
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur serveur

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header

definitions:
  LoginCredentials:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password

  SignUpCredentials:
    type: object
    required:
      - email
      - password
      - firstName
      - lastName
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password
      firstName:
        type: string
      lastName:
        type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/UserProfile'

  UserProfile:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string

  ProfileUpdate:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  Account:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      balance:
        type: number
      description:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      type:
        type: string
      category:
        type: string
      notes:
        type: string

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
